### ISSUE TITLE
toml-rb requirements

### ISSUE THREAD

**Issue by bdelamatre** [magnuslarsen/puppet-influxdb#1]
Repo is dependent on toml-rb which isn't present or available with stock Puppet installations.

Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Internal Server Error: org.jruby.exceptions.RaiseException: (LoadError) no such file to load -- toml

Following a similar requirement from puppetlabs/puppet_metrics_dashboard:
https://github.com/puppetlabs/puppet_metrics_dashboard#requirements

From puppetserver this results in:
[root@puppet ~]# puppetserver gem install toml-rb
Fetching: citrus-3.0.2.gem (100%)
Successfully installed citrus-3.0.2
Fetching: toml-rb-2.0.1.gem (100%)
ERROR:  Error installing toml-rb:
        toml-rb requires Ruby version >= 2.3.

It looks like ruby 2.3 wasn't added until Puppet 6. Trying an older version of toml-rb:

puppetserver gem install toml-rb -v 0.1.2 

resolves successfully. But installing this on either master, server or the client doesn't seem to resolve the dependency. I am guessing there are some undocumented dependencies and/or version requirements for using this plugin.,

**Comment by bdelamatre** [comment]
Following another suggestion, I restarted puppetserver after installing the toml and toml-rb -v0.1.2 gems and it seems to be working now.

**Comment by magnuslarsen** [comment]
Good catch - I have toml loaded from various modules...

I have the toml gem installed like this, on my puppetmaster (Puppet 5.5):
```puppet
package { 'toml':
  ensure   => 'installed',
  provider => 'puppetserver_gem',
}
```
...using this module: https://forge.puppet.com/puppetlabs/puppetserver_gem

I'll write something up after christmas :-) thanks for pointing it out!

**Comment by magnuslarsen** [comment]
I just uploaded a new version, with it documented. Thanks again for pointing it out :-)
