### ISSUE TITLE
undefined method `gsub' for nil:NilClass

### ISSUE THREAD

**Issue by AnonSS** [magnuslarsen/puppet-influxdb#7]
Hi,

When it comes to user creation, it requires that database and privilege be specified.  It then throws the above error.  My user config is as follows:

  users          => {
    'grafana'  => {
      'password' => 'k3jkji',
      privilege  => 'READ',
      database   => 'telegraf',
    },
    'telegraf' => {
      'password'  => 'kj4ki4',
      'privilege' => 'READ',
      'database'  => 'telegraf',
    },

I do have the dependencies installed.  Influxdb version:1.8.4.  Full error below.  Any ideas?

Error: /Stage[main]/Influxdb/Influxdb::User[telegraf]/Influxdb_user[influxdb_user_telegraf]: Could not evaluate: undefined method `gsub' for nil:NilClass

**Comment by magnuslarsen** [comment]
We agree that the database is also created, right? Like this:
```
  databases      => {
    'telegraf' => {
      'ensure' => present,
    }
  },
```

I would assume that is the error

**Comment by AnonSS** [comment]
Yes correct.

**Comment by AnonSS** [comment]
It looks like the user cannot have the same name as the database.  I chose a different username and all is good.
